health/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers

from api import views as api_views

router = routers.DefaultRouter()
router.register(r'users', api_views.UserViewset, base_name='users')
router.register(r'vendors', api_views.VendorViewset, base_name='vendors')
router.register(r'login', api_views.LoginView, base_name='login')
router.register(r'services', api_views.ServiceListView, base_name='services')
router.register(r'service_select', api_views.ServiceSelectView, base_name='service_select')
router.register(r'vendor_loc', api_views.VendorLocationView, base_name='vendor_loc')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^', include('ui.urls', namespace='ui')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

ui/urls.py
from django.conf.urls import include, url
from .import views

urlpatterns = [
	url(r'^$', views.HomeView.as_view(), name='home'),
	url(r'^dashboard/$', views.UserDashView.as_view(), name='userdash'),
	url(r'^dashboard/profile$', views.UserProfileView.as_view(), name='userprofile'),
	url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
	url(r'^place/(?P<prob_type>[0-9]+)/(?P<p_id>[0-9]+)/(?P<v_id>[0-9]+)/$', views.PlaceRequestView.as_view(), name='place'),
	url(r'^dashboard/map/(?P<prob_type>[0-9]+)/(?P<s_id>[0-9]+)/(?P<r_id>[0-9]+)$', views.UserMapView.as_view(), name='usermap'),

	url(r'^vdashboard/$', views.VendorDashboard.as_view(), name='vendordash'),
	url(r'^signup/$', views.SignupView.as_view(), name='signup'),
	url(r'^signup/services/(?P<u_id>[0-9]+)/$', views.VendorServicesView.as_view(), name='signup_services'),
]

ui/models.py
from django.db import models

# Create your models here.

ui/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from .mixins import LoginRequiredMixin, VendorRequiredMixin
from dbase.models import HUser, Vendor, Solution, Problem, Requirement, Request

def getUser(user):
	h = HUser.objects.get(user=user)
	return h

def getVendor(user):
	h = Vendor.objects.get(user=user)
	return h

# Create your views here.
class HomeView(TemplateView):
	template_name = "ui/home.html"

	def get(self, request):
		if request.user.is_authenticated and request.user.is_active:
			return redirect('ui:userdash')
		else:
			return render(request, self.template_name)

	def post(self, request):
		username = request.POST['email']
		password = request.POST['password']

		user = authenticate(username=username, password=password)
		try:
			huser = HUser.objects.get(user__username=username)
			if user is not None and user.is_active:
				login(request, user)
				return redirect('ui:userdash')

		except HUser.DoesNotExist:
			try:
				vendor = Vendor.objects.get(user__username=username)
				if user is not None and user.is_active:
					login(request, user)
					return redirect('ui:vendordash')
			except Vendor.DoesNotExist:
				pass


class UserDashView(LoginRequiredMixin, TemplateView):
	template_name = "ui/user_dash.html"

	def get(self, request):
		huser = getUser(request.user)
		solutions = Solution.objects.all()
		context = {
			"huser": huser,
			"solutions": solutions,
		}
		return render(request, self.template_name, context)

	def post(self, request):
		huser = getUser(request.user)
		if "social" in request.POST:
			solution = Solution.objects.get(id=int(request.POST['solution']))
			problem = Problem(desc=request.POST['comment'], solution=solution)
			problem.save()
			huser.problems.add(problem)
			huser.save()

			return redirect("ui:usermap", 1, solution.id, problem.id)
		elif "home" in request.POST:
			solution = Solution.objects.get(id=int(request.POST['solution_home']))
			requirement = Requirement(solution=solution, desc=request.POST['comment'])
			requirement.save()

			huser.requirements.add(requirement)
			huser.save()

			return redirect("ui:usermap", 2, solution.id, requirement.id)

class UserMapView(LoginRequiredMixin, TemplateView):
	template_name = "ui/user_map.html"

	def get(self, request, prob_type, s_id, r_id):
		solution = Solution.objects.get(id=int(s_id))
		vendors = Vendor.objects.filter(solutions__in=[solution])

		context = {
			"prob_type": int(prob_type),
			"vendors": vendors,
			"prob_id": int(r_id),
		}
		return render(request, self.template_name, context)

	def post(self, request, prob_type, s_id, r_id):
		print(request.POST.get('id'))

class PlaceRequestView(LoginRequiredMixin, TemplateView):
	template_name = "ui/place.html"

	def post(self, request, prob_type, p_id, v_id):
		if int(prob_type) == 1:
			problem = Problem.objects.get(id=int(p_id))
			vendor = Vendor.objects.get(id=int(v_id))
			huser = getUser(request.user)
			mrequest = Request(user=huser, vendor=vendor, problem=problem)
			mrequest.save()

		elif int(prob_type) == 2:
			requirement = Requirement.objects.get(id=int(p_id))
			vendor = Vendor.objects.get(id=int(v_id))
			huser = getUser(request.user)
			mrequest = Request(user=huser, vendor=vendor, requirement=requirement)
			mrequest.save()

		return render(request, self.template_name)

class LogoutView(View):
	def get(self, request):
		logout(request)
		return redirect('ui:home')		

class VendorDashboard(VendorRequiredMixin, TemplateView):
	template_name = "ui/vendor_dash.html"

	def get(self, request):
		vendor = getVendor(request.user)
		requests = Request.objects.filter(vendor=vendor)
		context = {
			"requests": requests,
		}
		return render(request, self.template_name, context)

class SignupView(TemplateView):
	template_name = "ui/signup.html"

	def post(self, request):
		name = request.POST['name']
		email = request.POST['email']
		phone = request.POST['phone']
		password = request.POST['password']
		usertype = request.POST['usertype']

		user = User.objects.create_user(email, email, password)
		user.save()

		if usertype == "vendor":
			vendor = Vendor(user=user, name=name, phone=phone)
			vendor.save()
			return redirect("ui:signup_services", vendor.id)
		else:
			huser = HUser(user=user, name=name, phone=phone)
			huser.save()

			return redirect("ui:home")

class VendorServicesView(TemplateView):
	template_name = "ui/vendor_services.html"

	def get(self, request, u_id):
		solutions = Solution.objects.all()
		context = {
			"solutions": solutions,
		}
		return render(request, self.template_name, context)

	def post(self, request, u_id):
		vendor = Vendor.objects.get(id=u_id)
		solution_ids = request.POST.getlist('solution')
		print(solution_ids)
		for sol_id in solution_ids:
			print(sol_id)
			sol = Solution.objects.get(id=sol_id)
			vendor.solutions.add(sol)
		vendor.save()

		return redirect("ui:home")

class UserProfileView(LoginRequiredMixin, TemplateView):
	template_name = "ui/user_profile.html"

	def get(self, request):
		huser = getUser(request.user)
		context = {
			"huser": huser,
		}
		return render(request, self.template_name, context)

templates/ui/base.html
<!DOCTYPE html>
<html>
<head>
	<title> Clean City </title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/flat-ui.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
	{% block css %}{% endblock %}
</head>
<body>
{% block content %}
{% endblock %}

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/flat-ui.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/ui/home.html
{% extends "ui/base.html" %}

{% block content %}
	<h3 style="color: #fff;text-align: center;margin-bottom:-40px;font-size: 50px;">Clean City</h3>
<div class="login">
    <div class="login-screen">
      	<div class="login-form">
      		<form action="" method="POST">
      		{% csrf_token %}
	      		<h2 class="heading">Login</h2>
	        	<div class="form-group">
	          		<input type="text" class="form-control login-field" value="" placeholder="Email" id="login-name" name="email">
	          		<label class="login-field-icon fui-user" for="login-name"></label>
	        	</div>

	            <div class="form-group">
	              	<input type="password" class="form-control login-field" value="" placeholder="Password" id="login-pass" name="password">
	              	<label class="login-field-icon fui-lock" for="login-pass"></label>
	            </div>

	        	<input class="btn btn-primary btn-lg btn-block" href="#" type="submit" value="Login">
	        	<p class="login-link" style="color:#34495e !important;">New User?<a href="{% url 'ui:signup' %}"> <span class="color-green">Signup here!</span></a></p>
        	</form>
    	</div>
	</div>
</div>
{% endblock %}

templates/ui/place.html
{% extends "ui/base.html" %}

{% block content %}
 	<h4 style="color:#fff;text-align:center;margin-top:260px;"> 
 	Thank you for placing the request. The vendor will get back to you soon. <br><a style="color: #34495e;font-size: 20px;" href="{% url 'ui:home' %}">
 	Back to Home Page</a></h4>
{% endblock %}

templates/ui/signup.html
{% extends "ui/base.html" %}
{% block content %}
    <div class="login">
        <div class="login-screen">
          <form action="" method="POST">
          	{% csrf_token %}
          	<div class="login-form">
              <h2 class="heading">New User? Sign Up here!</h2>
            	<div class="form-group">
              		<input type="text" class="form-control login-field" value="" placeholder="Enter your name" id="login-name" name="name">
              		<label class="login-field-icon fui-user" for="login-name"></label>
            	</div>

              <div class="form-group"> 
                  <input type="email" class="form-control login-field" value="" placeholder="Enter your email-id" id="login-mail" name="email">
                  <label class="login-field-icon fui-mail" for="login-pass"></label>
              </div>

	            <div class="form-group">
	              	<input type="password" class="form-control login-field" value="" placeholder="Password" id="login-pass" name="password">
	              	<label class="login-field-icon fui-lock" for="login-pass"></label>
	            </div>

              <div class="form-group">
                <input type="text" class="form-control login-field" value="" placeholder="Phone number" id="login-number" name="phone">
                <label class="login-field-icon fui-phone" for="login-number"></label>
              </div>

              
              <div class="row demo-row">
                <div class="col-xs-3">
                  <label class="radio"> 
                  <input type="radio" name="usertype" id="usertype" value="user" data-toggle="radio">
                  User
                  </label>
                </div>
              
                <div class="col-xs-3">
                  <label class="radio">
                  <input type="radio" name="usertype" id="usertype" value="vendor" data-toggle="radio" checked="">
                  Vendor
                  </label>
                </div>
              </div>
              

            	<input type="submit" value="Next" class="btn btn-primary btn-lg btn-block" href="index.html">
            	<a class="login-link" href="{% url 'ui:home' %}">Already have an account?</a>
        	</div>
          </form>	
    	</div>
    </div>
{% endblock %}

templates/ui/user_dash.html
{% extends "ui/base.html" %}

{% block content %}
<div class="row demo-row">
  <div class="col-xs-12">
    <nav class="navbar navbar-inverse navbar-embossed" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
          <span class="sr-only">Toggle navigation</span>
        </button>
        <a class="navbar-brand" href="#">Clean City</a>
      </div>
            
      <div class="collapse navbar-collapse" id="navbar-collapse-01">
        <ul class="nav navbar-nav navbar-right">
         <li><a href="{% url 'ui:userprofile' %}">Profile</a></li>
          <li><a href="{% url 'ui:logout' %}">Logout</a></li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </nav><!-- /navbar -->
  </div>
</div>

<div class="row demo-tiles">
  <div class="col-xs-1"></div>
  <div class="col-xs-5">
  	<form action="" name="social" method="POST">
  		{% csrf_token %}
	    <div class="tile">
	      <h3 class="tile-title" style="padding-bottom:20px;">Keeping my surroundings clean</h3>
	      <textarea class="textarea-content" placeholder="Leave your comment here!" name="comment"></textarea>
	      <h5 class="tile-title" style="padding-bottom:10px;text-align:left;margin-left:65px;padding-top:10px;">Requesting for </h5>
	      <div class="row demo-row" style="margin-left: 40px;">

	      {% for solution in solutions %}
	      <div class="col-xs-6">
	        <label class="radio">
	          <input type="radio"  value="{{ solution.id }}"  name="solution">
	          {{ solution.title }}
	        </label>
	      </div>
	      {% endfor %}

	    </div>
	    <input type="submit" value="Save" class="btn btn-primary btn-large btn-block" href="google_map.html" name="social" >
	    </div>
    </form>
  </div>

  <div class="col-xs-1"></div>

  <div class="col-xs-4">
  <form action="" method="POST" name="home">
  	{% csrf_token %}
    <div class="tile">
      <h3 class="tile-title" style="padding-bottom:20px;">Home = Hygiene</h3>
      <textarea class="textarea-content" placeholder="Leave your comment here!" name="comment"></textarea>

      <h5 class="tile-title" style="padding-bottom:10px;text-align:left;margin-left:45px;padding-top:10px;">Requesting for </h5>

      <div class="row demo-row">
  		{% for solution in solutions %}
	       <div class="col-xs-6">
	        <label class="radio">
	          <input type="radio" value="{{ solution.id }}" name="solution_home">
	          {{ solution.title }}
	        </label>
	      </div>
	    {% endfor %}
     </div>
	    <input type="submit" value="Save"  class="btn btn-primary btn-large btn-block" href="google_map.html" name="home">
   
  	</div>
  </form>
  </div>

  <div class="col-xs-1"></div>
</div>
{% endblock %}

templates/ui/user_map.html
{% extends "ui/base.html" %}

{% block css %}
  <style type="text/css">
    #map {
      width: 100%;
      height: 510px;
      background-color: #CCC;
      margin: 0 auto;
    }
  </style>
{% endblock %}

{% block content %}
<div id="map">
  
</div>


<!-- <button style="margin-top:20px;margin-left:50%;">Submit</button> -->
{{ prob_type }}
{% if prob_type == 1 %}
<button type="button" class="btn btn-block btn-lg btn-inverse" data-toggle="modal" data-target="#fakelink" style="margin-top:25px;margin-left:45%;width:10%;">Submit</button>
{% else %}
<button type="button" class="btn btn-block btn-lg btn-inverse" data-toggle="modal" data-target="#fakelink1" style="margin-top:25px;margin-left:45%;width:10%;">Submit</button>
{% endif %}

<div class="modal fade" id="fakelink" tabindex="" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel" style="color:#1abc9c !important;font-size:20px;">Thank you</h4>
      </div>
      <div class="modal-body">
        <span style="font-size:16px;">Your valuable response has been noted. The issue will be addressed soon.</span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary"><a href="{% url 'ui:home' %}" style="color:#fff;">Back to Homepage</a></button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="fakelink1" tabindex="" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#1abc9c;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel" style="color:#34495e !important;font-size:20px;">Vendor List</h4>
      </div>
      <div class="modal-body" style="background-color:#34495e;">
      <h3 style="color:#1abc9c;font-size:22px;margin-top:-3px;">Vendors who can respond to your request</h3>
        {% for vendor in vendors %}
         <form action="{% url 'ui:place' prob_type prob_id vendor.id %}" method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col-xs-6">
              <p class="vendor-name login-field-icon fui-user"> {{ vendor.name }} </p>
            </div>
            <div class="col-xs-2"></div>
            <div class="col-xs-4">
              <p class="vendor-contact fui-mic"> {{ vendor.phone }}</p>
            </div>
          </div>
          
          <div class="row">
            <div class="col-xs-8">
              <p class="fui-document vendor-address"> {{ vendor.address }}</p>
            </div>
            <div class="col-xs-4">
              <input type="submit" value="Place request" class="btn btn-primary btn-lg btn-block" href="" style="width:90%;">
            </div>
          </div>
           <hr>
          </form>
         {% endfor %} 
		        
          <div class="modal-footer" style="border:none;">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary"><a href="{% url 'ui:home' %}" style="color:#fff;">Back to Homepage</a></button>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

{% block js %}
<script type="text/javascript" src="js/jquery.min.js"></script>
<!-- <script type="text/javascript" src="js/bootstrap.min.js"></script> -->
<script type="text/javascript" src="js/flat-ui.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
        async defer></script>
<script type="text/javascript">


  function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: -34.397, lng: 150.644},
    zoom: 6
  });
  var infoWindow = new google.maps.InfoWindow({map: map});

  // Try HTML5 geolocation.
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var pos = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };

      infoWindow.setPosition(pos);
      infoWindow.setContent('Location found.');
      map.setCenter(pos);
    }, function() {
      handleLocationError(true, infoWindow, map.getCenter());
    });
  } else {
    // Browser doesn't support Geolocation
    handleLocationError(false, infoWindow, map.getCenter());
  }
}

function handleLocationError(browserHasGeolocation, infoWindow, pos) {
  infoWindow.setPosition(pos);
  infoWindow.setContent(browserHasGeolocation ?
                        'Error: The Geolocation service failed.' :
                        'Error: Your browser doesn\'t support geolocation.');
}

</script>
{% endblock %}

templates/ui/user_profile.html
{% extends "ui/base.html" %}

{% block content %}
{% load staticfiles %}
<div class="row demo-tiles" style="margin-top:40px;">
  <div class="col-xs-3"></div>
  <div class="col-xs-6">
    <div class="tile">
      <div class="row">
        <div class="col-xs-12">
          <img src="{% static 'img/user.jpg' %}" width="220px" height="200px;">
        </div>
        <div class="row">
          <div class="col-xs-12" style="text-align:center">
          <h3 style="font-size:28px;"> {{ huser.name }} </h3>
          <p style="font-size:22px;margin-bottom:-5px;margin-top:5px;"> {{ huser.user.email }} </p>
          <p style="font-size:22px;"> {{ huser.phone }} </p>
        </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-3"></div>
</div>
{% endblock %}

templates/ui/vendor_dash.html
{% extends "ui/base.html" %}

{% block content %}

<div class="row demo-row">
  <div class="col-xs-12">
    <nav class="navbar navbar-inverse navbar-embossed" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
          <span class="sr-only">Toggle navigation</span>
        </button>
        <a class="navbar-brand" href="#">Clean City</a>
      </div>
            
      <div class="collapse navbar-collapse" id="navbar-collapse-01">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"> Profile </a></li>
          </li>
          <li><a href="{% url 'ui:logout' %}"> Logout </a></li>
          </li>
        </ul>            
      </div><!-- /.navbar-collapse -->
    </nav><!-- /navbar -->
  </div>
</div>

<div class="row demo-row">
  <div class="col-xs-3"></div>
  <div class="col-xs-9">
    <div class="row demo-tiles">
      <div class="col-xs-1"></div>
      <div class="col-xs-6">
        <div class="tile">
          <h3 class="tile-title" style="padding-bottom:20px;font-size:20px !important;">Requests for your service</h3>
          <h4 style="font-size:18px;text-align:left;">Requested by,</h4>
          {% for req in requests %}
          <div class="row demo-row user-content">
              <div class="col-xs-6">
                <p>{{ req.user.name }}</p>
              </div>
              <div class="col-xs-6">
                <p>{{ req.user.phone }}</p>
              </div>
              <div class="col-xs-12" style="margin-top:-35px;margin-bottom:10px;font-style: italic;">
              {% if req.requirement %}
              	{{ req.requirement.desc }}
              {% else %}
              	{{ req.problem.desc }}
              {% endif %}
              </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/ui/vendor_services.html
{% extends "ui/base.html" %}

{% block css %}

  <style type="text/css">
  #map {
    width: 450px;
    height: 400px;
    background-color: #CCC;
    margin-bottom: 20px;
  }
  </style>
{% endblock %}

{% block content %}
    <div class="login">
        <div class="login-screen">
          <form action="" method="POST">
           {% csrf_token %}
          	<div class="login-form vendor-form">
              <h2 class="heading">What services do you provide?</h2>
              
              <div class="row demo-row">
              {% for solution in solutions %}
              
                <div class="col-xs-6">
                  <label class="checkbox">
                <input type="checkbox" value="{{ solution.id }}" name="solution" data-toggle="checkbox">
                {{ solution.title }}
                </label>
              </div>
              
              {% endfor %}
              </div>
              <div class="row demo-row">
              <h5 class="location-map">Select your location: </h5>
                <div class="col-xs-6">
                  <div id="map" style="margin-left:50px !important;">
                    
                  </div>
                </div>
              </div>

              <div class="row" style="color:#34495e !important;margin-bottom:30px;">
                <h5 class="range-selector">Select a range(kilometers):</h5>
                <div class="col-xs-12">
                  <div id="slider" class="ui-slider">
                    <div class="ui-slider-segment" style="margin-top:10px;">
                      <p>0</p>
                    </div>
                    <div class="ui-slider-segment"></div>
                    <div class="ui-slider-segment" style="margin-left:48%;margin-top:10px;">
                      <p>10</p>
                    </div>
                    <div class="ui-slider-segment" style="float:right;margin-right:10px;margin-top:10px;">
                      <p>20</p>
                    </div>
                  </div>
                </div>
              </div>
              <input type="submit" value="Sign up" class="btn btn-primary btn-lg btn-block" href="index.html">
        	</div>
          </form>
    	</div>
    </div>
{% endblock %}

{% block js %}
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
        async defer></script>
<script type="text/javascript">
  var $slider = $("#slider");
  if ($slider.length > 0) {
    $slider.slider({
    min: 1,
    max: 5,
    value: 3,
    orientation: "horizontal",
    range: "min"
  }).addSliderSegments($slider.slider("option").max);
}
</script>
<script type="text/javascript">
  // function initMap() {
  //   var mapDiv = document.getElementById('map');
  //   var map = new google.maps.Map(mapDiv, {
  //     center: {lat: 44.540, lng: -78.546},
  //     zoom: 8
  //   });
  // }

  function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: -34.397, lng: 150.644},
    zoom: 6
  });
  var infoWindow = new google.maps.InfoWindow({map: map});

  // Try HTML5 geolocation.
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var pos = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };

      infoWindow.setPosition(pos);
      infoWindow.setContent('Location found.');
      map.setCenter(pos);
    }, function() {
      handleLocationError(true, infoWindow, map.getCenter());
    });
  } else {
    // Browser doesn't support Geolocation
    handleLocationError(false, infoWindow, map.getCenter());
  }
}

function handleLocationError(browserHasGeolocation, infoWindow, pos) {
  infoWindow.setPosition(pos);
  infoWindow.setContent(browserHasGeolocation ?
                        'Error: The Geolocation service failed.' :
                        'Error: Your browser doesn\'t support geolocation.');
}

</script>
{% endblock %}